translation_unit =
    { top_level_declaration } ;

top_level_declaration =
    FN , function_declaration ;

function_declaration =
    type , IDENTIFIER , "(" , [ parameter_list ] , ")" , block ;

parameter_list =
    parameter , { "," , parameter } ;

parameter =
    type , IDENTIFIER ;

block =
    "{" , { statement } , "}" ;

statement =
    block                       |
    expression_statement        |
    type , variable_declaration |
    IF , if_statement           |
    WHILE , while_statement     |
    FOR , for_statement         |
    RETURN , return_statement   |
    ";"                         ;

expression_statement =
    expression , ";" ;

variable_declaration =
    init_declarator_list , ";" ;

init_declarator_list =
    init_declarator , { "," , init_declarator } ;

init_declarator =
    IDENTIFIER , [ "=" , expression ] ;

if_statement =
    "(" , expression , ")" , block ,
    { ELSE , IF , "(" , expression , ")" , block } ,
    [ ELSE , block ];

while_statement =
    "(" , expression , ")" , block ;

for_statement =
    "(" , [ type , init_declarator ] , ";" , [ expression ] , ";" , [ expression ] , ")" , block ;

return_statement =
    [ expression ] , ";" ;

expression_list =
    expression , { "," , expression } ;

expression =
    assign_expression ;

assign_expression =
    logical_or_expression , [ assign_op , assign_expression ] ;

assign_op =
    "=" |
    "+=" |
    "-=" |
    "*=" |
    "/=" |
    "%=" ;

logical_or_expression =
    logical_and_expression                                |
    logical_or_expression , "||" , logical_and_expression ;

logical_and_expression =
    relational_expression                                 |
    logical_and_expression , "&&" , relational_expression ;

relational_expression =
    add_expression                                         |
    relational_expression , relational_op , add_expression ;

relational_op =
    "==" |
    "!=" |
    ">=" |
    "<=" |
    ">"  |
    "<"  ;

add_expression =
    mul_expression                           |
    add_expression , add_op , mul_expression ;

add_op =
    "+" |
    "-" ;

mul_expression =
    prefix_expression                           |
    mul_expression , mul_op , prefix_expression ;

mul_op =
    "*" |
    "/" |
    "%" ;

prefix_expression =
    postfix_expression            |
    prefix_op , prefix_expression ;

prefix_op =
    "&"              |
    "*"              |
    "-"              |
    "!"              |
    "++"             |
    "--"             |
    "(" , type , ")" ;

postfix_expression =
    primary_expression              |
    postfix_expression , postfix_op ;

postfix_op =
    "[" , expression , "]"                            |
    "[" , [ expression ] , ":" , [ expression ] , "]" |
    "(" , [ expression_list ] , ")"                   ;

primary_expression =
    literal                                   |
    IDENTIFIER                                |
    "[" , [ expression_list ] , "]"           |
    "(" , expression , ")"                    ;

type =
    type_name , { type_specifier } ;

type_specifier =
    [ CONST ] , "*"             |
    [ CONST ] , "[]"            |
    "[" , INTEGER_LITERAL , "]" ;

type_name =
    "Unit" |
    "I32"  |
    "U8"   |
    "Bool" ;

literal =
    INTEGER_LITERAL   |
    STRING_LITERAL    |
    CHARACTER_LITERAL |
    TRUE              |
    NULL              |
    FALSE             ;
